const SETTINGS_KEY='vexs_4_3';let SETTINGS=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');if(typeof SETTINGS.vibration==='undefined')SETTINGS.vibration=true;function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(SETTINGS));}
function now(){const d=new Date();return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');}
function dateStr(){return new Date().toLocaleDateString();}
function tick(){let lc=document.getElementById('lockClock');if(lc)lc.textContent=now();let ld=document.getElementById('lockDate');if(ld)ld.textContent=dateStr();}
setInterval(tick,1000);tick();
const APPS=[{id:'telefono',name:'Teléfono',icon:'telefono.png'},{id:'mensajes',name:'Mensajes',icon:'mensajes.png'},{id:'galeria',name:'Galería',icon:'galeria.png'},{id:'navegador',name:'Navegador',icon:'navegador.png'}];
const BOOT_MAX_MS=16000;
function bootSequence(){const vid=document.getElementById('bootVideo');let finished=false;function finish(){if(finished) return;finished=true;proceedToLock();}if(vid&&typeof vid.play==='function'){vid.addEventListener('ended',finish);setTimeout(finish,BOOT_MAX_MS+600);}else{setTimeout(finish,BOOT_MAX_MS);}}
function proceedToLock(){document.getElementById('boot').classList.add('hidden');document.getElementById('boot').setAttribute('aria-hidden','true');const lock=document.getElementById('lock');lock.classList.remove('hidden');lock.setAttribute('aria-hidden','false');document.getElementById('homeGesture').style.display='block';}
function checkFileExists(path,cb){if(!path) return cb(false);const img=new Image();let h=false;img.onload=()=>{if(!h){h=true;cb(true);}};img.onerror=()=>{if(!h){h=true;cb(false);}};img.src=path;setTimeout(()=>{if(!h){h=true;cb(false);}},900);}
function verifyPlaceholders(){const req=['telefono.png','mensajes.png','galeria.png','navegador.png'];req.forEach(p=>checkFileExists(p,exists=>{if(!exists){const el=document.createElement('div');el.className='error-box';el.innerHTML=`⚠️ Falta <strong>${p}</strong>. Súbelo a la raíz.`;document.body.appendChild(el);}}));}
function enableGestures(){// LOCK: swipe UP to unlock
  const lock=document.getElementById('lock');let sY_lock=0;lock.addEventListener('touchstart',e=>sY_lock=e.touches[0].clientY,{passive:true});lock.addEventListener('touchend',e=>{const dy=sY_lock - e.changedTouches[0].clientY;if(dy>60){if(SETTINGS.vibration && navigator.vibrate) navigator.vibrate(40);goHome();}}, {passive:true});
  // HOME gesture visual feedback
  const gesture=document.getElementById('homeGesture');let gS=0;gesture.addEventListener('touchstart',e=>gS=e.touches[0].clientY,{passive:true});gesture.addEventListener('touchend',e=>{const dy=gS - e.changedTouches[0].clientY; if(dy>20){gesture.style.transform='translateY(-6px)';setTimeout(()=>gesture.style.transform='none',200);}},{passive:true});
  // APP: swipe UP to CLOSE app (user requested)
  const appWindow=document.getElementById('appWindow');let aS=0;appWindow.addEventListener('touchstart',e=>aS=e.touches[0].clientY,{passive:true});appWindow.addEventListener('touchend',e=>{const dy=aS - e.changedTouches[0].clientY;if(dy>60){closeApp();}}, {passive:true});}
function goHome(){document.getElementById('lock').classList.add('hidden');document.getElementById('home').classList.remove('hidden');document.getElementById('dock').style.display='flex';}
function openApp(id){const app=APPS.find(a=>a.id===id)||{name:id};const content=document.getElementById('appContent');content.innerHTML=`<div style="padding-top:28px"><h1>${app.name}</h1><p>App en pantalla completa — desliza hacia arriba para salir.</p></div>`;const win=document.getElementById('appWindow');document.getElementById('home').classList.add('hidden');win.classList.remove('hidden');win.style.display='flex';win.classList.add('app-open-anim');win.setAttribute('aria-hidden','false');if(SETTINGS.vibration && navigator.vibrate) navigator.vibrate(20);content.focus();}
function closeApp(){const win=document.getElementById('appWindow');win.classList.add('hidden');win.style.display='none';document.getElementById('home').classList.remove('hidden');document.getElementById('appContent').innerHTML='';}
// dock buttons hookup
function setupDock(){document.querySelectorAll('.dock-btn').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.app;openApp(id);}));}
// init
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('homeGesture').style.display='none';document.getElementById('dock').style.display='none';verifyPlaceholders();enableGestures();setupDock();setTimeout(()=>bootSequence(),200);});window.vexs={openApp,closeApp,saveSettings,SETTINGS};